### ISSUE TITLE
Search engine requests

### ISSUE THREAD

**Issue by wong2** [wong2/chatgpt-google-extension#109]
Supported search engines are listed in the README https://github.com/wong2/chat-gpt-google-extension#supported-search-engines

New search engine support can be requested here in the comment.

**Comment by tugdual-harel** [comment]
Hi, thanks for the great work. I use StartPage, so if it is possible to support it someday, it would be great.

**Comment by MinmoTech** [comment]
I'd like to request the searx search engine as per https://github.com/wong2/chat-gpt-google-extension/issues/101

It is an [open-source metasearch engine](https://en.wikipedia.org/wiki/Searx) and there are multiple public instances hosted with the most popular seemingly being searx.be

Ideally you could add custom instance urls in the settings, similar to how the extension [MALSync allows you to add plex/emby/jellyfin domains](https://github.com/MALSync/MALSync/wiki/Emby-Plex).

**Comment by sreid99** [comment]
Hi, Could you consider adding [Neeva](https://neeva.com/) ?

**Comment by ylluminate** [comment]
The, objectively, best instance of Searx is `https://searx.tiekoetter.com/`. That would be the one to add since it has the most refined UI/UX compared to other instances.

**Comment by targed** [comment]
> The, objectively, best instance of Searx is `https://searx.tiekoetter.com/`. That would be the one to add since it has the most refined UI/UX compared to other instances.

I use https://searx.tiekoetter.com/ as my daily one as well, and I was able to get it working for that one by just adding `,'#sidebar_results'` to the search-engine-configs.mjs file under the searx entry. This is because different searx instances have different containers for the sidebar. 

Here is the edited code:

`searx: {
    inputQuery: ["input[name='q']"],
    sidebarContainerQuery: ['#sidebar','#sidebar_results'],
    appendContainerQuery: [],
  },`

However, this only really gets a few other searx instances working but leaves a lot of them listed at https://searx.space/ out. 

Hope this helps!

**Comment by bmihovski** [comment]
Thank you for the great add-on.
Can you add support for Qwant search engine https://www.qwant.com/

**Comment by nightscape** [comment]
Thank you for creating this nice extension!
Could you please also add Ecosia (see #162)?

**Comment by weiqiyue** [comment]
About adding a custom search engine, you can find the sidebar of the corresponding engine and the class name or id name of the search result container to modify the source code, which is better than painting a gourd...

**Comment by brackhap** [comment]
can you please add support to whoogle?

**Comment by okiejnm** [comment]
¿podrías considerar agregar you.com?

**Comment by 00028** [comment]
add opnxng.com

**Comment by lolsu-de** [comment]
Hello, I would love to see support for [Ecosia](https://ecosia.org/). I know it's not that popular globally but the germans would appreciate it

**Comment by nightscape** [comment]
@lolsu-de see https://github.com/wong2/chat-gpt-google-extension/issues/109#issuecomment-1369788022

**Comment by lolsu-de** [comment]
> @lolsu-de see https://github.com/wong2/chat-gpt-google-extension/issues/109#issuecomment-1369788022

Oh lol, don't know how I've missed that but the more the merrier, right

**Comment by josStorer** [comment]
@nightscape @lolsu-de 
Maybe you can try [my fork](https://github.com/josStorer/chatGPT-search-engine-extension), which supports Ecosia and Android phones, and you can customize the configuration to add supported sites

**Comment by lewisje** [comment]
I see that DuckDuckGo is supported, but could you add the ad-free start.duckduckgo.com and filtered safe.duckduckgo.com domains?

**Comment by gitiy1** [comment]
Hello, I would like to see support for [Presearch](https://presearch.com/). It's a Web3 search engine which is similar to Brave Search but more focus on perfomance and privacy. Now Presearch  is the dafault search engine on European Android Devices and is known to many developers. Adding Presearch would help developers that focus on Web3 development. Thanks a lot for your hard work!

**Comment by Qizhen-Yang** [comment]
Offering a list of domains in the options page should be a better solution for all those search engine requests.
Also consider turning the chatgpt card into a popup window so as to fit different websites.

**Comment by acbary** [comment]
Hi. I would like to see support for [Daum](https://search.daum.net/search?nil_suggest=btn&w=tot&DA=SBC&q=chatgpt). Koreans would appreciate it after Naver. And It is my most favorate search engine. Please consider it.

**Comment by a-aznar** [comment]
@lolsu-de @banifou Added Ecosia in this PR: https://github.com/wong2/chatgpt-google-extension/pull/217

**Comment by wong2** [comment]
I decided to not accepting new search engines, please fork the project in that case.
