### ISSUE TITLE
Add support for OpenAI API keys

### ISSUE THREAD

**Issue by jackoneschuk** [wong2/chatgpt-google-extension#116]
ChatGPT is unlikely to remain free forever so support for uploading an [OpenAI API key](https://beta.openai.com/docs/api-reference/authentication) is necessary for this browser extension to remain usable in the long run. As an added benefit this will address issues #108 and #112 since the paid OpenAI API is not experiencing the same downtime/restrictions as ChatGPT while providing similar functionality at de minimis cost (fractions of a cent per search).

<img width="1306" alt="Screenshot 2022-12-14 at 10 01 05 AM" src="https://user-images.githubusercontent.com/113490931/207674481-53574bcd-6ee3-4446-8869-50de41351a49.png">

**Comment by wong2** [comment]
ChatGPT doesn't have a paid api yet

**Comment by Kcin1993** [comment]
It is currently difficult to achieve the same level of experience as ChatGPT with the completion API that is available from OpenAI. 

For example, on ChatGPT, it is possible to provide explanations for questions that have been asked before, and the content of these explanations can be coherent. However, the completion API is limited by the max_tokens, which means that the content of the question cannot be too long, making it difficult to achieve a coherent experience. 

If there is a way to overcome this, I am also interested. Otherwise, we will really have to wait for the API related to ChatGPT to be available.

**Comment by kertser** [comment]
May be you can summarize the previous answer and provide this summary as a context to the model to match the max_tokens size?

**Comment by yodaluca23** [comment]
Wouldn't this also fix us having to pass Cloudflare pretty much check every time we use it, since going through the API is official and doesn't have Cloudflare checks, rather than what we have now, which I'm not sure how it works, but it uses the user's website client instead...

**Comment by wong2** [comment]
@yodaluca23 That's right

**Comment by wong2** [comment]
I'm planning to implement this, as ChatGPT API is coming

**Comment by Echoleung** [comment]
> GPT-3 is not as good as ChatGPT in this case, so I'll wait for ChatGPT official API

The ChatGPT official API leaked.

**Comment by wong2** [comment]
@Echoleung I know, this extension already supported it.

**Comment by 0xdevalias** [comment]
> The ChatGPT official API leaked.

> I know, this extension already supported it.

@Echoleung @wong2 Curious.. where did the official API leak? Tried googling but not managing to come up with any good answers.

**Comment by yodaluca23** [comment]
When I select the Offical API and select the "text-chat-davinci-002-20221122" option, it works, and I have no payment info connected to my account, is their some free credits? Or is it unlimitedly free? Please Let me know, thanks!

**Comment by Kcin1993** [comment]
@yodaluca23  No it's not free. You can check your OpenAI account. There is a credit of 18$ for 3 months.

**Comment by yodaluca23** [comment]
> @yodaluca23  No it's not free. You can check your OpenAI account. There is a credit of 18$ for 3 months.

Thank you, I figured it out here:
![image](https://user-images.githubusercontent.com/67206487/217143957-c9175b20-6353-464d-8b74-390ef4720f86.png)
there should be a notice somewhere that everyone does have $18 in free trial credits… And that this will use them if you enable the API option…
