### ISSUE TITLE
Improve the Readme for a better Explanation

### ISSUE THREAD

**Issue by DeepakKumarKhatri** [wong2/chatgpt-google-extension#143]
**What's the Issue?**
Currently, this readme has different headings for explaining what this repo is all about? But now this extension is being used by multiple users, and these headings are not enough to explain how it works and all, so it would be better if we could modify the readme in a good way for better interactions with the new contributors.

**Changes I would like to add**
 - Make the readme descriptive but also concise.
 - Meaningful headings
 - Gifs of the working of this extension
 - Same theme for the whole readme

**Comment by wong2** [comment]
Actually, I'm not sure what improvement you mean. But you can try and create a pull request

**Comment by DeepakKumarKhatri** [comment]
Thank you @wong2 for responding!
I'm working on it.
