### ISSUE TITLE
Please login and pass Cloudflare check at chat.openai.com

### ISSUE THREAD

**Issue by Temanor** [wong2/chatgpt-google-extension#161]
There was another issue like this, but it was closed even though it didn't work for me.
I am on firefox and using the brave search engine.
I tried to switch the search engine to google but it still wouldn't load.

**Comment by wong2** [comment]
Can you post a video?

**Comment by zebratt** [comment]
same issue, i'm using google and it shows "Please login and pass Cloudflare check at chat.openai.com"

**Comment by wong2** [comment]
Does it show even after you just login

**Comment by Temanor** [comment]
https://user-images.githubusercontent.com/91745601/210405113-4b095251-d017-4377-b2e0-6faaefb6eb68.mp4

Idk what else to show in the video :/
I got the same result when using the google search engine

**Comment by eleqtrizit** [comment]
I'm having the same problem.  I am logged into ChatGPT and the link the extension provides opens right up in another tab.  The extension seems to think I have a problem I don't.

**Comment by wong2** [comment]
@Temanor Thanks for the video, is that a special version of Firefox?

**Comment by wong2** [comment]
@eleqtrizit What browser are you using? Please note, OpenAI requires you to pass a security check every once in a while

**Comment by Temanor** [comment]
I am using firefox with custom css

**Comment by jorit-vasconezgerlach** [comment]
i had the same problem and solved it trough deactivating following setting
https://github.com/wong2/chat-gpt-google-extension#how-to-make-it-work-in-brave

**Comment by Temanor** [comment]
> i had the same problem and solved it trough deactivating following setting https://github.com/wong2/chat-gpt-google-extension#how-to-make-it-work-in-brave

I am not on brave though. I only use the brave search engine, but I still get the same error even if I change to google.

**Comment by Jasmine-liang** [comment]
I'm having the same problem on Chrome...

**Comment by randomishwalk** [comment]
@wong2 - are there other Brave specific settings you'd recommend users tweak for better compatibility with your extension? You already pointed out one in your [troubleshooting section](https://github.com/wong2/chat-gpt-google-extension#troubleshooting) but curious if you / others have found others

**Comment by wong2** [comment]
@randomishwalk nope

**Comment by skypoc** [comment]
> pleasepasscloudflare.mp4 
> Idk what else to show in the video :/ I got the same result when using the google search engine
> 
> Edit: I also tried 2 different OpenAI accounts. One connected with google and one with email.

I have the same problem.
What is the tag management plug-in in the video? This is too cool!

**Comment by Temanor** [comment]
> > pleasepasscloudflare.mp4
> > Idk what else to show in the video :/ I got the same result when using the google search engine
> > Edit: I also tried 2 different OpenAI accounts. One connected with google and one with email.
> 
> I have the same problem. What is the tab management plug-in in the video? This is too cool!

I am using TreeStyleTabs customised for my setup. The setup for firefox can be downloaded at [this Github](https://github.com/AmadeusWM/dotfiles-hyprland)

**Comment by GollyJer** [comment]
Same problem. Anyone find a solution?

I'm on macOS if that makes a diff.

**Comment by Fastjur** [comment]
This seems to be an issue with people having 'sandboxed' tabs.
Privacy-oriented browsers, or extensions that add more privacy may be preventing the Cloudflare check to be accessed between tabs. So to ChatGPT / Cloudflare it looks like a completely fresh request everytime, and hence you would have to do this check everytime.

**Comment by Temanor** [comment]
> This seems to be an issue with people having 'sandboxed' tabs. Privacy-oriented browsers, or extensions that add more privacy may be preventing the Cloudflare check to be accessed between tabs. So to ChatGPT / Cloudflare it looks like a completely fresh request everytime, and hence you would have to do this check everytime.

I tried to turn off the multi-container add-on, but I still get the same message.

**Comment by xianfengzhu340** [comment]
I got the same problem, and chatgpt works well in its own Chrome tab.
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/6387593/213420966-03821c16-7966-4906-8c13-5eecc340107c.png">

**Comment by pdario** [comment]
Same here, it worked once I disabled AdGuard: what exception should I add to AdGuard to make it work?

**Comment by wootwoot1234** [comment]
Same issue here.  

I disabled ad blocker and that didn't fix it.  

Not sure if this is related, but I get this error on the chatgpt page:

<img width="1429" alt="Screenshot 2023-01-26 at 8 25 02 AM" src="https://user-images.githubusercontent.com/419609/214860872-ee64b490-1767-47c8-be3b-7acce006159e.png">

**Comment by Danielnaor** [comment]
> This seems to be an issue with people having 'sandboxed' tabs. Privacy-oriented browsers, or extensions that add more privacy may be preventing the Cloudflare check to be accessed between tabs. So to ChatGPT / Cloudflare it looks like a completely fresh request everytime, and hence you would have to do this check everytime.

same here

**Comment by wootwoot1234** [comment]
I'm using a standard version of Chrome.  I don't think I've enabled any "sandbox" settings.

**Comment by GongZhengMe** [comment]
I have the same problem with the latest Chrome Version @109.0.5414.119. And it never work success.It‘s always need login in any search.And I test when I disable the other security extension or ad block.And it can't login in extension page.I think you can add a login page in the extension page.
![image](https://user-images.githubusercontent.com/26669429/215302054-7319ad28-d061-4f79-bfe9-71777c272497.png)

**Comment by flaming** [comment]
same here
![image](https://user-images.githubusercontent.com/1780629/215655550-755568b5-c5ad-40bb-aa05-2d76ddbe7e8a.png)

**Comment by roo12589** [comment]
i have the same problem,what should i do to solve that? the extension dont work.

**Comment by cyber1o1** [comment]
Same problem, try to find some setting like brave://settings/shields in chrome but failed . 
And then  I change to use brave browser just get this [can't login to chatgpt](https://i.imgur.com/ri5bGAy.png)

What else I can do.
Please help.

**Comment by bbxtudios** [comment]
Same here...

Brave.

**Comment by songjie55** [comment]
When to fix this bug，come on.

**Comment by qq280948982** [comment]
i have the same problem...

**Comment by wootwoot1234** [comment]
@wong2 do you have a minute to take a look at this?

**Comment by lmarch2** [comment]
The same problem

**Comment by Spp595** [comment]
the same thing in chrome

**Comment by wong2** [comment]
Brave users please read the solution in README

**Comment by xiaotingsong** [comment]
The same problem in Google

**Comment by SwartzMss** [comment]
> i had the same problem and solved it trough deactivating following setting https://github.com/wong2/chat-gpt-google-extension#how-to-make-it-work-in-brave

i still cannot find brave setting

**Comment by xianfengzhu340** [comment]
I solved this problem by setting my own OpenAI API key in the options page
<img width="482" alt="image" src="https://user-images.githubusercontent.com/6387593/216531257-5755e11f-4998-46b0-965c-af9893df0dc5.png">

**Comment by Spp595** [comment]
> Я решил эту проблему, установив свой собственный ключ API OpenAI на странице параметров. <img alt="изображение" width="482" src="https://user-images.githubusercontent.com/6387593/216531257-5755e11f-4998-46b0-965c-af9893df0dc5.png">

 Сначала не понял что за страница параметров, оказалось что это страница настройки расширения и мне это помогло.

 At first I didn't understand what the parameters page was, it turned out that it was the extension settings page and it helped me.

**Comment by Temanor** [comment]
I don't know if there was an update or anything, but now it seems to be working just fine.

**Comment by lmarch2** [comment]
It works now by adding a OpenAI API key in the setting page

**Comment by wslyt** [comment]
I updated the version of the extension and added a OpenAI API key in the new settings page. The extension is now working properly.

**Comment by beibeibest** [comment]
why it still doesn't work in chrome for me? I have tried all these methods above.

**Comment by jindalni** [comment]
I was able to solve this by switching my internet connection, so its possible that OpenAi is doing some IP level tracking.

**Comment by andorba** [comment]
> i had the same problem and solved it trough deactivating following setting https://github.com/wong2/chat-gpt-google-extension#how-to-make-it-work-in-brave

Thx

**Comment by bigplayer-ai** [comment]
I keep getting Please login and pass Cloudflare check at chat.openai.com.
I thought maybe you could add auto login/enter to chatgpt every set time. so no need for us to keep passing the cloudfare check at chat.openai.com

**Comment by sebastian-montoya** [comment]
To fix the problem on Brave:
Go to chat.openai.com and disable brave shield.

![image](https://user-images.githubusercontent.com/23144482/216808479-adb33e2c-9c20-4759-b4c5-9822a3d551da.png)

**Comment by bigplayer-ai** [comment]
I’m using google chromeOn 5 Feb 2023, at 10:10, sebas.montoya ***@***.***> wrote:﻿
To fix the problem on Brave:
Go to chat.openai.com and disable brave shield.

**Comment by Temanor** [comment]
I did not enter any API key anywhere, and it started working fine for me after the latest update.

**Comment by aTreey** [comment]
I used the AI Provider in ChatGPT for Google, the plugin was able to work.

**Comment by WillYujin** [comment]
**To solve this problem in Chrome**: 
1) enter the extension settings. 
2) there will be an option to enter the AI provider and secret APIKey. There will also be a link for you to create your own APIKey.  (https://platform.openai.com/account/api-keys)
3)Make your APIKey in the marked place and save. It shou

**Comment by bigplayer-ai** [comment]
> **To solve this problem in Chrome**:
> 
> 1. enter the extension settings.
> 2. there will be an option to enter the AI provider and secret APIKey. There will also be a link for you to create your own APIKey.  (https://platform.openai.com/account/api-keys)
>    3)Make your APIKey in the marked place and save. It shou

I don't have any quota (api credit) left to use this api key. :(
I thought of a solution to make custom script to open chat.openai.com at background every 30mins

**Comment by shuaihuaiyi** [comment]
Same problem in Chrome, I can open the ChatGPT page and chat normally, but I am still encountering an error message saying 'Please login and pass Cloudflare check at chat.openai.com'. 

The plugin configuration is set to default, and my Chrome version is 109.0.5414.119. Any further information needed？

**Comment by sup-lh** [comment]
There is an option to enter AI provider and secret APIKey
There will also be a link for you to create your own APIKey ( https://platform.openai.com/account/api-keys )
Make your APIKey where marked and save
Then fill in and use normally

**Comment by fnhe** [comment]
> **To solve this problem in Chrome**:
> 
> 1. enter the extension settings.
> 2. there will be an option to enter the AI provider and secret APIKey. There will also be a link for you to create your own APIKey.  (https://platform.openai.com/account/api-keys)
>    3)Make your APIKey in the marked place and save. It shou

it works for me. Thanks, bro

**Comment by hfl112** [comment]
> **To solve this problem in Chrome**:
> 
> 1. enter the extension settings.
> 2. there will be an option to enter the AI provider and secret APIKey. There will also be a link for you to create your own APIKey.  (https://platform.openai.com/account/api-keys)
>    3)Make your APIKey in the marked place and save. It shou

It works for me!! Thanks

**Comment by HancockY** [comment]
> 

it works

**Comment by rime6102** [comment]
I set the my APIKey.
but, still not work.

**Comment by wong2** [comment]
@rime6102 which model are you using?

**Comment by gengjiawen** [comment]
@wong2 Is it possible to auto solve CF check in browser env using solution similar to https://github.com/fuergaosi233/wechat-chatgpt#captchas

**Comment by wong2** [comment]
@gengjiawen that's not possible

**Comment by sspro-lldream** [comment]
Why does this kind of problem occur? Does the chrom browser intelligently solve it through its own API key? Does it default to your own API key?

**Comment by JackDinn** [comment]
Just installed addon on firefox / on linux manjaro , same error, i dont have an api but i didnt see anything in the addon settings asking for one. I can access gpt fine. Then i thought id check the twitter link listed on the firefox addon page @chatgptforseach and the twitter page has been suspended for violations, i got concerned so iv uninstalled the addon. I might try it again if i can see a fix for the "Please login and pass Cloudflare check at"

**Comment by wong2** [comment]
@JackDinn I'm pretty sure that you're describing another extension, because our Twitter handle is @chatgpt4google
This is our Firefox link: https://addons.mozilla.org/en-US/firefox/addon/chatgpt-for-google/

**Comment by JackDinn** [comment]
> @JackDinn I'm pretty sure that you're describing another extension, because our Twitter handle is @chatgpt4google This is our Firefox link: https://addons.mozilla.org/en-US/firefox/addon/chatgpt-for-google/

Yea sorry, i had just realized you are right, i was muddled ^^,

**Comment by martin-braun** [comment]
@wong2 It's not working for me in Brave with the same error message either, but I disabled "Prevent sites from fingerprinting me based on my language preferences" in the shield preferences. Btw, I think it should work with that option enabled. ChatGPT itself can figure out the language by itself as well.

**Comment by robomaniac** [comment]
> I solved this problem by setting my own OpenAI API key in the options page <img alt="image" width="482" src="https://user-images.githubusercontent.com/6387593/216531257-5755e11f-4998-46b0-965c-af9893df0dc5.png">

I had same issue and created my own API, now it works. Thank you

**Comment by squarewang007** [comment]
I solved this problem by setting  chrome-extension://jgjaeacdkonaoafenlfkkkmbaopkbilf/options.html
<img width="599" alt="image" src="https://user-images.githubusercontent.com/28798102/219848607-4026645f-f342-4e6c-a746-115190484d2f.png">

**Comment by AntoninoMacri** [comment]
> I solved this problem by setting chrome-extension://jgjaeacdkonaoafenlfkkkmbaopkbilf/options.html <img alt="image" width="599" src="https://user-images.githubusercontent.com/28798102/219848607-4026645f-f342-4e6c-a746-115190484d2f.png">

Ty this works for me

**Comment by yuanshun-guo** [comment]
> > I solved this problem by setting chrome-extension://jgjaeacdkonaoafenlfkkkmbaopkbilf/options.html <img alt="image" width="599" src="https://user-images.githubusercontent.com/28798102/219848607-4026645f-f342-4e6c-a746-115190484d2f.png">
> 
> Yes, this worked for me. Ty!
> 
> In summary:
> 
> 1. You need to log in to https://chat.openai.com/chat with your account or create one
> 2. then go to: https://platform.openai.com/account/api-keys and generate your key.
> 3. Then copy the created key and paste it into the AI provider > OpenAI API > API KEY box that you can find at the link: chrome-extension://jgjaeacdkonaoafenlfkkkmbaopkbilf/options.html.

This worked for me. Thanks!

**Comment by zchoi** [comment]
The above solution is correct but **NOTE that**: 
If you set OpenAI API in your AI Provider, each time the ChatGPT response for Google search will be charged, that is, each request to OpenAI's API will be charged ≈$0.002, and we have a maximum usage cap of $18.00
![image](https://user-images.githubusercontent.com/30498168/220055241-5af7625b-a9e1-44d0-bc59-1305e558812b.png)

**Comment by StevenGrow** [comment]
I'm having the same problem on Chrome...

**Comment by zchoi** [comment]
one solution works for me:
1. Login to ChatGPT, and pin the page on chrome：
![image](https://user-images.githubusercontent.com/30498168/220854570-7ae04702-78f6-45e6-96b8-d3142fc3c46f.png)
2. choose AI provider as ChatGPT Webapp：
![image](https://user-images.githubusercontent.com/30498168/220854682-acedebfa-d3ce-48c5-b3b4-ede1ed7a9584.png)
3. The response of ChatGPT worked：
![image](https://user-images.githubusercontent.com/30498168/220855117-9693ee13-2efa-466b-be86-a4b58f70538e.png)

**Comment by AntoninoMacri** [comment]
> ≈$0.002, and we have a maximum usage cap of $18.00

Ty!

**Comment by bigplayer-ai** [comment]
For me on edge, I PIN the chatgpt website tab, While preventing it from sleep.
No Issues so far.
![Clip_20230301_123742](https://user-images.githubusercontent.com/119108387/222115497-46f9eeec-68bd-4147-bf88-ecaa7742c114.png)

**Comment by Temanor** [comment]
I think this is resolved now

**Comment by wangyingang** [comment]
> one solution works for me:
> 
> 1. Login to ChatGPT, and pin the page on chrome：
>    ![image](https://user-images.githubusercontent.com/30498168/220854570-7ae04702-78f6-45e6-96b8-d3142fc3c46f.png)
> 2. choose AI provider as ChatGPT Webapp：
>    ![image](https://user-images.githubusercontent.com/30498168/220854682-acedebfa-d3ce-48c5-b3b4-ede1ed7a9584.png)
> 3. The response of ChatGPT worked：
>    ![image](https://user-images.githubusercontent.com/30498168/220855117-9693ee13-2efa-466b-be86-a4b58f70538e.png)

I've tried it, but it doesn't work for me.

**Comment by Argornst** [comment]
> one solution works for me:
> 
> 1. Login to ChatGPT, and pin the page on chrome：
>    ![image](https://user-images.githubusercontent.com/30498168/220854570-7ae04702-78f6-45e6-96b8-d3142fc3c46f.png)
> 2. choose AI provider as ChatGPT Webapp：
>    ![image](https://user-images.githubusercontent.com/30498168/220854682-acedebfa-d3ce-48c5-b3b4-ede1ed7a9584.png)
> 3. The response of ChatGPT worked：
>    ![image](https://user-images.githubusercontent.com/30498168/220855117-9693ee13-2efa-466b-be86-a4b58f70538e.png)

Doesn't work for me

**Comment by brunogsa** [comment]
Nothing worked for me, despite the API Key usage :/

**Comment by teddimitrov** [comment]
Microsoft Edge
Version 112.0.1722.64 (Official build) (64-bit)

API key method does not work. Keeps prompting to sign in.
