### ISSUE TITLE
Support more AI providers

### ISSUE THREAD

**Issue by wong2** [wong2/chatgpt-google-extension#198]
This extension currently uses the unofficial ChatGPT API, which is free but requires constant Cloudflare security check, which results in unpleasant UX. So I'm thinking of support more AI providers, from which a user can select by themselves in the option page.

Some candidates:
* OpenAI GPT-3 API https://github.com/wong2/chat-gpt-google-extension/issues/116
* Upcoming OpenAI official ChatGPT API
* YouChat https://github.com/wong2/chat-gpt-google-extension/issues/154

Anymore suggestions?

**Comment by zhang36790315** [comment]
always show “Please login and pass Cloudflare check at http://chat.openai.com” chrome  版本 109.0.5414.120  How to deal with it。Logged into chatgpt

**Comment by zhang36790315** [comment]
always show “Please login and pass Cloudflare check at http://chat.openai.com” chrome  版本 109.0.5414.120  How to deal with it。Logged into chatgpt
