### ISSUE TITLE
"stop generating" integration?

### ISSUE THREAD

**Issue by anandijain** [wong2/chatgpt-google-extension#200]
Sometimes I google something, but then go to chatgpt to ask it something else, which then gives 
`Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute.`

They recently introduced a stop generating button on the main site. Would it be hard to put that in the extension? If not, it would be a nice feature.

Thank you so, so much for this extension. It is truly wonderful!

**Comment by wong2** [comment]
Yeah it is possible to add this feature

**Comment by chrahman** [comment]
Yes plz add this feature

**Comment by CODe5753** [comment]
@wong2 
It seems that clicking the 'Stop generating' button in ChatGPT does not trigger any API calls. How do you plan to implement this feature in chatgpt-google-extension?

**Comment by chrahman** [comment]
> @wong2 It seems that clicking the 'Stop generating' button in ChatGPT does not trigger any API calls. How do you plan to implement this feature in chatgpt-google-extension?

It is possible, using abortControllar and sending abort signal in API fetch options.

**Comment by giyyapan** [comment]
This feature is implemented in version 2.0.1.

Please upgrade to 2.0.1 from Chrome store:
https://chrome.google.com/webstore/detail/chatgpt-for-google/jgjaeacdkonaoafenlfkkkmbaopkbilf
