### ISSUE TITLE
Nothing shows up when searching

### ISSUE THREAD

**Issue by DrinkingJoe** [wong2/chatgpt-google-extension#201]
**Describe the bug**
Nothing shows up when searching
![image](https://user-images.githubusercontent.com/63132234/214194005-4354bc51-f264-41c6-96b8-17c37279d200.png)
![image](https://user-images.githubusercontent.com/63132234/214194057-73af4137-9ecc-4d7c-a490-f294a880e6f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera GX

**Comment by wong2** [comment]
That's weird, can you try Chrome?

**Comment by DrinkingJoe** [comment]
Can confirm that it works on chrome. I would like to point out that on chrome, the extension has full access, while on Opera GX it is in the "No Acces Needed" section of extensions.
Opera:
![image](https://user-images.githubusercontent.com/63132234/214629826-01c2a3e5-99cd-424e-a109-0dfe93ef0972.png)
Chrome:
![image](https://user-images.githubusercontent.com/63132234/214629945-8950d258-3a60-4bfb-a4c5-28b11abfdc1d.png)

**Comment by FlyPhoenix52** [comment]
I got the same problem, I tried on chrome and It worked. I don't understand why it's not working on Opera cause chrome extenssions are all for Opera too. I hope this will be fixed soon !

**Comment by CCost** [comment]
I found a fix for Opera GX ! 
![image](https://user-images.githubusercontent.com/32577231/215619737-4339c37d-999b-4837-9c9c-fcc2552f5099.png)
Go to extensions, and enable "Allow access to search page results"
Hope this helps!

**Comment by DragonPow** [comment]
I have this check but it still error, Trigger Mode "Always" is ok

**Comment by blipblopok** [comment]
> I found a fix for Opera GX ! ![image](https://user-images.githubusercontent.com/32577231/215619737-4339c37d-999b-4837-9c9c-fcc2552f5099.png) Go to extensions, and enable "Allow access to search page results" Hope this helps!
Great, I should have thought of it since Chrome works perfectly, why not Opera GX when all I had to do was activate this.
