### ISSUE TITLE
 Auto delete conversations generated by search is grayed out.

### ISSUE THREAD

**Issue by bigplayer-ai** [wong2/chatgpt-google-extension#203]
**Describe the bug**

Auto delete conversations generated by search is grayed out.
![Auto delete conversations generated by search is grayed out.](https://user-images.githubusercontent.com/119108387/214541279-6a3bc716-874a-4780-ae47-ef99f9538a4a.png)

**Desktop (please complete the following information):**
OS: Windows 11 22h2 build 22621
Browser chrome Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by wong2** [comment]
I think your real issue is the auto deletion doesn't work.

Related: https://github.com/wong2/chat-gpt-google-extension/issues/160

**Comment by bigplayer-ai** [comment]
Yes
I still experience the same issue, I want to delete the conversations from chatgpt website.
