### ISSUE TITLE
auth/session GET request failing only on my account/laptop

### ISSUE THREAD

**Issue by jindalni** [wong2/chatgpt-google-extension#208]
Hi!

Thanks for the extension, really useful.

I have been trying to build something similar for a different use case and was using the underlying libraries that you have built for connecting with OpenAI. It used to work fine initially but off late I realised that the session/ api call continues to fail on my device whereas it works fine on a different device.

Once it started failing, it started happening for chat-gpt-google extension as well and not despite logging in, I continue to see the 403 on the session API call.

Few thing I have tried:

- I am able to use the ChatGpt on OpenAI website
- I tried clearing all cookies on my device but still not helping.
- I tried creating a new account but still not working.

Would really appreciate if you have any ideas on how to fix this.

Thanks!

<img width="1674" alt="Screenshot 2023-01-28 at 10 42 14 AM" src="https://user-images.githubusercontent.com/108979593/215243488-3e589f06-8939-44f3-9c18-baaf2d232cd2.png">

**Comment by wong2** [comment]
I have no idea, the cloudflare check is a black box
