### ISSUE TITLE
OpenAI requires passing a security check every once in a while.

### ISSUE THREAD

**Issue by zznova** [wong2/chatgpt-google-extension#211]
**Describe the bug**
Always alerts "OpenAI requires passing a security check every once in a while." even just  logged in openai these days.

windows10 ,chrome latest

**Comment by neurocis** [comment]
2nd, from Opera w/"Allow access to search results" enabled.

**Comment by Loongphy** [comment]
You can solve the problem using API keys, but it requires payment, with  a free trial avaible.
![image](https://user-images.githubusercontent.com/42089082/216489400-2a442731-f1b4-4c45-9b05-3fee2a269b07.png)
