### ISSUE TITLE
"We're currently processing too many requests" error but official site works.

### ISSUE THREAD

**Issue by 404b** [wong2/chatgpt-google-extension#216]
**Describe the bug**
"We're currently processing too many requests" error but official site works.

**Desktop (please complete the following information):**
 - Windows
 - chrome Version 109.0.5414.88

**Comment by chendotjs** [comment]
I can confirm encountering the same issue.

**Comment by khengyun** [comment]
i have same isssue

**Comment by wong2** [comment]
Can you try v1.16.0? which is live on Chrome Web Store

**Comment by 404b** [comment]
> Can you try v1.16.0? which is live on Chrome Web Store

working. thanks 👍
