### ISSUE TITLE
"That model does not exist" error

### ISSUE THREAD

**Issue by jagadish834** [wong2/chatgpt-google-extension#219]
Failed to load response from ChatGPT:
{"detail":{"message":"That model does not exist","type":"invalid_request_error","param":null,"code":null}}
![error](https://user-images.githubusercontent.com/121537553/216239520-b15a5bdf-1cfa-4fcf-8acb-72861cff2c99.JPG)
![error1](https://user-images.githubusercontent.com/121537553/216239523-a575afb6-4260-432a-b5ad-269ca1afcc2d.JPG)

**Comment by alighamdan** [comment]
i just changed this line: https://github.com/wong2/chatgpt-google-extension/blob/main/src/background/chatgpt.ts#L53
from: text-davinci-002-render
to: text-davinci-002-render-next
and build it using npm
and its working with me

**Comment by wong2** [comment]
This has been fixed in v1.16.0
Released in Chrome Web Store

**Comment by wong2** [comment]
https://github.com/wong2/chatgpt-google-extension/commit/71e465acf6b701a24cd06758781823ee3329de3d

**Comment by wong2** [comment]
Seems they changed it back to `text-davinci-002-render`....

**Comment by XueMeijing** [comment]
> Seems they changed it back to `text-davinci-002-render`....

😅😅
