### ISSUE TITLE
When I want to start always said like this "Failed to load response from ChatGPT: {"detail":"An error ocurred. Try refreshing your browser."}. Why?

### ISSUE THREAD

**Issue by Arseio** [wong2/chatgpt-google-extension#221]
**Describe the bug**Always said Failed to load please try to refresh you browser

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]Windows 11
 - Browser [e.g. chrome, brave]Google Chrome

**Comment by Arseio** [comment]
Please help , because everything was working yesterday. And I tried to refresh page few times and computer ,but issue is still there.

**Comment by wong2** [comment]
Related to https://github.com/wong2/chatgpt-google-extension/issues/219#issuecomment-1413944721

Fix release is pending for review
