### ISSUE TITLE
Doesnt show a response

### ISSUE THREAD

**Issue by nshahadat** [wong2/chatgpt-google-extension#222]
Failed to load response from ChatGPT:
{"detail":"An error ocurred. Try refreshing your browser."}

this comes on every search

**Comment by wong2** [comment]
Make sure you're using the latest version! v1.16.3

**Comment by Cazeh** [comment]
<img width="1320" alt="grafik" src="https://user-images.githubusercontent.com/11591428/218310272-bbdfefe7-d80b-4505-8cf0-c6e0fec94a3d.png">
Same here
