### ISSUE TITLE
Update logo to be less busy and simpler at tiny sizes

### ISSUE THREAD

**Issue by ababx** [wong2/chatgpt-google-extension#223]
**Describe the bug**
Current icon in the browser chrome has too much detail which makes it look busy at its size
<img width="164" alt="image" src="https://user-images.githubusercontent.com/29093/216794361-00a4e5ec-fc16-46a2-a749-aae3554c582e.png">

Propose swapping it with this icon which has similar color for maintaining brand continuity and it uses hexagon element from openai logo to denote connection with chatGPT.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/29093/216794483-7af7b8a4-453a-40ca-9441-c6ffbd23ce99.png">

![chatGPTforGooglelogo_new@1x](https://user-images.githubusercontent.com/29093/216794490-fc739085-7324-47d4-9c43-1b8ac5e7cdf8.png)
<img width="128" alt="chatGPTforGooglelogo_new@2x" src="https://user-images.githubusercontent.com/29093/216794492-b0fe2866-2652-4fa9-892c-7954962e1592.png">
![chatGPTforGooglelogo_new](https://user-images.githubusercontent.com/29093/216794493-ced66740-d84b-450a-8c49-baa4cfcd2325.svg)

**Comment by ababx** [comment]
Happy to also update all the chrome extension store images. Just let me know.

**Comment by wong2** [comment]
Wow, thanks. But I'd like to keep the old logo for the moment.
