### ISSUE TITLE
How to use the my own session/access token for openai?

### ISSUE THREAD

**Issue by arkilis** [wong2/chatgpt-google-extension#226]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]
Firefox

@wong2 感谢大佬提供了这个插件，很厉害，想请教如何处理session/access token，是用户自己登陆的token还是预置了一个login token? 谢谢

**Comment by wong2** [comment]
用户在chatgpt网页登录后的token
