### ISSUE TITLE
I understand that you need to survive, but implementing advertisements with no notice or options to disable isn't nice

### ISSUE THREAD

**Issue by AshleyJackson** [wong2/chatgpt-google-extension#234]
The first intial implementation seems to be here: https://github.com/wong2/chatgpt-google-extension/commit/d32f2260bc611d7761a9f4d8a11af22b3d13a351 (I could be wrong)
With results nowadays looking like below
![image](https://user-images.githubusercontent.com/12793989/217448202-a3f3adbd-028c-4090-8d4f-8c8f83ac0120.png)

If you had have made it optional, asked the person if it was okay to be advertised to, I wouldn't have mind. Simple Boolean, Yes or No at first install. I actually would have said yes, your implementation is good and doesn't seem to send much data to your api from what I can tell and the api level response isn't bad either.
![image](https://user-images.githubusercontent.com/12793989/217450256-8c797394-df57-42ec-8b54-7065ea42a820.png)

You've made a cool app that works really well and many people enjoy. Why shouldn't you be able to benefit from it financially?

According to Google you've nearly got a million users. I sincerely hope you're making good bank, but you've sadly lost me as a user of this extension.

Please make analytics and advertisements optional.

Thanks.

**Comment by wong2** [comment]
Thanks for your advice, we're exploring new ways of monetization, so I think maybe the ad would disappear!
