### ISSUE TITLE
Feature: Use PerplexityAI

### ISSUE THREAD

**Issue by Aymkdn** [wong2/chatgpt-google-extension#235]
Hi,

Thanks for this extension.

ChatGPT is not up-to-date and over capacity these days ("ChatGPT is at capacity right now"). I don't know if it's possible, but there is another AI that I found better than ChatGPT: https://www.perplexity.ai/ – maybe it could be use as a replacement?

I didn't find any API doc on their website, so not sure if it would be possible…

**Comment by wong2** [comment]
Yeah I've thought about that, but perplexity also has Cloudflare protection which will make this very hard.
