### ISSUE TITLE
Change behavior of Enter key to submit the query rather than doing a new line.

### ISSUE THREAD

**Issue by Sirbab** [wong2/chatgpt-google-extension#239]
Currently, in the extension window, if you press enter, it just goes down a line, functioning similar to Shift-Enter in other programs.  Please make enter submit the query for QOL sake.

**Comment by wong2** [comment]
Nice idea

**Comment by vrindavan** [comment]
How to change this? Mine still enters a new line on enter.

**Comment by Sirbab** [comment]
I can confirm it also still is an issue.
