### ISSUE TITLE
Error when using with ChatGPT Plus account

### ISSUE THREAD

**Issue by nate456789** [wong2/chatgpt-google-extension#243]
Like openAI accounts we need to be able to use our ChatGPT Plus accounts.
Thanks

**Comment by jamie-cao** [comment]
Upvote for this issue! I have just upgraded to ChatGPT Plus, and the extension doesn't work anymore. It will always spit out this error:

Failed to load response from ChatGPT:
{"detail":"An error ocurred. Try refreshing your browser."}

Please accommodate ChatGPT Plus users soon! This would definitely help a lot of people. Thank you so much!

**Comment by wong2** [comment]
Since I have no access to ChatGPT Plus yet, it's difficult for me to develop this. Need help from someone who has access.

**Comment by wong2** [comment]
Supported in v1.17.0

**Comment by phamquiluan** [comment]
Confirm v1.17.0 support plus version. You can build the project manually and load it to your browser without wait for official release.

**Comment by ozbillwang** [comment]
Nice jobs, if need any tests with Plus, let me know.

**Comment by still-dreaming-1** [comment]
> pending on Web Store reviews

Please explain

**Comment by ozbillwang** [comment]
> > pending on Web Store reviews
> 
> Please explain

So the reason why we use OpenAI, not Google, because we don't need help from us for this type of questions now.

You can get help by yourself now

![image](https://user-images.githubusercontent.com/8954908/218293355-8d5b0a95-e9be-4b56-a24f-88653f0f9f0f.png)

**Comment by randomsnowflake** [comment]
Just writing to confirm the GIT version has the bug fixed. 

Now if it could only change the model to the faster one as well ...

**Comment by still-dreaming-1** [comment]
> > > pending on Web Store reviews
> > 
> > 
> > Please explain
> 
> So the reason why we use OpenAI/ChatGPT, not Google now, because it gives the answer directly.
> 
> You should do that always from now on, more than ask for help for these type of questions any more.
> 
> ![image](https://user-images.githubusercontent.com/8954908/218293355-8d5b0a95-e9be-4b56-a24f-88653f0f9f0f.png)

I thought maybe it meant awaiting more user reviews (plural) on the web store before it will be available to more people on the web store. It's nice that they are trying to keep some level of QA in place, but annoying when you are just waiting for a bug fix for a bug that only cropped up after you started paying for the "better" version of something.

**Comment by still-dreaming-1** [comment]
I was able to install v1.17.0 through the web store. It does fix the issue.
