### ISSUE TITLE
Is it possible to integrate Turbo model for ChatGPT Plus ?

### ISSUE THREAD

**Issue by jason1122g** [wong2/chatgpt-google-extension#255]
Recently, ChatGPT has added a Turbo Model option to the ChatGPT Plus plan, which responds very quickly.  
It would be great if this option could be integrated into this extension! 

<img width="683" alt="ChatGPT Models" src="https://user-images.githubusercontent.com/5618429/218470848-dc24856c-dcdb-4a97-a06c-d8ea2fecd0ad.png">

```json
{
    "models": [
        {
            "slug": "text-davinci-002-render-paid",
            "max_tokens": 4097,
            "title": "Default",
            "description": "The standard (Plus) ChatGPT model",
            "tags": [
                "concise"
            ]
        },
        {
            "slug": "text-davinci-002-render-sha",
            "max_tokens": 4097,
            "title": "Turbo",
            "description": "Optimized for speed (alpha, currently available to plus users)",
            "tags": []
        }
    ]
}

```

https://github.com/wong2/chatgpt-google-extension/blob/v1.17.0/src/background/providers/chatgpt.ts#L64

**Comment by jason1122g** [comment]
Turbo Model has become the default model, so this extension might not need to update :thinking: 

```json
{
  "models": [
    {
      "slug": "text-davinci-002-render-sha",
      "max_tokens": 4097,
      "title": "Default",
      "description": "The default ChatGPT model",
      "tags": []
    },
    {
      "slug": "text-davinci-002-render-paid",
      "max_tokens": 4097,
      "title": "Legacy",
      "description": "The legacy ChatGPT model",
      "tags": [
        "concise"
      ]
    }
  ]
}
```

**Comment by uquince6** [comment]
become the default model but very recently right?

**Comment by jason1122g** [comment]
I received this update notification only after opening the webpage an hour ago.

**Comment by sirpeebs** [comment]
ok I'm late the dance on this but can someone point me to any reading info on why ChatGPT Plus is rocking text-davinci-002 rather than text-davinci-003?

**Comment by wong2** [comment]
I agree it's better to let user choose which model to use.

**Comment by wong2** [comment]
It seems the legacy model will be removed sometime, so I think the current "default" approach is ok.
