### ISSUE TITLE
Support Laptops

### ISSUE THREAD

**Issue by psc8** [wong2/chatgpt-google-extension#259]
**Describe the bug**
On a laptop I have a limited screen width. This add-on sets a too large margin on the right side: 

![image](https://user-images.githubusercontent.com/97252617/219034173-624ff33c-7c90-415b-8ed7-53fd451e8bdf.png)

rhs-margin is set to calc(50vw + -669px), where 669px is far too large, should rather be set to 0 for laptops:

![image](https://user-images.githubusercontent.com/97252617/219034927-fc4f5572-27b7-4f79-92b1-19677ed96ea8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Comment by wong2** [comment]
That's not set by this extension, but Google itself.
