### ISSUE TITLE
Please login and pass Cloudflare check at chat.openai.com

### ISSUE THREAD

**Issue by guyleung2** [wong2/chatgpt-google-extension#268]
Please login and pass Cloudflare check at [chat.openai.com](https://chat.openai.com/)

After logged in Chat GPT, still nothing.
![image](https://user-images.githubusercontent.com/125851906/220014848-ec6aa8b5-d93c-4efc-b92e-b31dc66f3707.png)

**Comment by weiqiyue** [comment]
mo too~

**Comment by weiqiyue** [comment]
me too
