### ISSUE TITLE
Extension has been acquired... but by whom?

### ISSUE THREAD

**Issue by corneliusroemer** [wong2/chatgpt-google-extension#269]
I noticed you mentioned that this extension has been acquired. Can you tell by whom? OpenAI?

**Comment by corneliusroemer** [comment]
@wong2, can you explain why you closed this as completed without giving an answer?

**Comment by CODe5753** [comment]
I'm curious why this open source project is no longer being updated. Who will be updating it in the future?

**Comment by wong2** [comment]
It may or may not keep open source in the future

**Comment by dannyhpy** [comment]
You need **at least** to mention this in the extension itself and on [Twitter](https://twitter.com/chatgpt4google).

If this extension is going in the hands of someone else, you should disclose who and why.

Your extension has access to all common search engines. This is just common sense to be transparent on this when your extension has access to the most visited websites.

**Comment by MMMXXXZZZ** [comment]
@wong2 Please disclose that the code has been acquired and is no longer open source in the webstore and in the extension itself.

**Comment by EDM115** [comment]
@corneliusroemer yes, OpenAI acquired this  
![image](https://github.com/wong2/chatgpt-google-extension/assets/82015596/4b6b7031-e499-49c1-ba4f-f3f7d667d61e)

**Comment by wong2** [comment]
That's not true. It says "not part of"

**Comment by EDM115** [comment]
ah my bad I read too fast 😭
