### ISSUE TITLE
Delete conversations in chat of chatgpt

### ISSUE THREAD

**Issue by JibranZeb** [wong2/chatgpt-google-extension#275]
**Describe the bug**
when I open chat.openai.com my account is full of "New Chat". Please change it to delete automatically all the questions searched on Google.

**Desktop (please complete the following information):**
 - Window 10 Professional
 - Chrome

**Comment by giyyapan** [comment]
This is a bug in version 2.0.0, and it's fixed in version 2.0.1.

Please upgrade to 2.0.1 from Chrome store:
https://chrome.google.com/webstore/detail/chatgpt-for-google/jgjaeacdkonaoafenlfkkkmbaopkbilf

**Comment by MTheSmartestM** [comment]
will there be an update for FireFox as this issue still exists here

**Comment by giyyapan** [comment]
Yes, the version 2.0.1 is already submitted to Firefox store about a week ago. Due to Firefox's stricter review policy and slow respond time, this extension is still under review and we are still trying to communicate with them.

**Comment by MTheSmartestM** [comment]
Woul i be able to take the .xpi file and run the extension using that?

**Comment by bigplayer-ai** [comment]
I am on edge with latest version of both. I still experience the same issue, The conversation search on google is not cleared out.

**Comment by MTheSmartestM** [comment]
> I am on edge with latest version of both. I still experience the same issue, The conversation search on google is not cleared out.

Both what?

Also i figured out that it only doesnt clear when the conversation is cut off
meaning i do another google search or smt
