### ISSUE TITLE
Why create a new conversation every time you search for new content?

### ISSUE THREAD

**Issue by NCPSNetworks** [wong2/chatgpt-google-extension#277]
**Describe the bug**
Why create a new conversation every time you search for new content?
I saw a lot of "New Chat" after searching a lot of content

**Desktop (please complete the following information):**
 - Windows 10
 - Edge

**Comment by giyyapan** [comment]
This is a bug in version 2.0.0, and it's fixed in version 2.0.1.

Please upgrade to 2.0.1 from Chrome store:
https://chrome.google.com/webstore/detail/chatgpt-for-google/jgjaeacdkonaoafenlfkkkmbaopkbilf

**Comment by TonyYanOnFire** [comment]
Yeah, I got the same question. IMO it's totally doable to just keep all question in on conversation
