### ISSUE TITLE
Support recently introduced model of ChatGPT API: `gpt-3.5-turbo`

### ISSUE THREAD

**Issue by Taewan-P** [wong2/chatgpt-google-extension#293]
Currently, this extension only supports ChatGPT API with `text-davinci-003`.

According to the [documentation](https://platform.openai.com/docs/guides/chat), API with new model `gpt-3.5-turbo` is released and it performs at a similar capability to `text-davinci-003` but at 10% the price per token. So it is recommended for most use cases.

It would be great if this extension supports the new model as well.

**Comment by lujijiang** [comment]
see https://github.com/ajiang-open/chatgpt-google-extension.git

**Comment by Taewan-P** [comment]
@lujijiang Thanks for your work! 
As this repo is no longer maintaining, I should look into the forked ones.
