### ISSUE TITLE
Malware Notification on Google Chrome

### ISSUE THREAD

**Issue by rosx27** [wong2/chatgpt-google-extension#357]
I've installed this extension via official store. but sometime this week, a google popped up warning me that the extension contains a malware, i ignored it thinking that its just a false alarm, however, while browsing, i stumble upon [this news](https://thehackernews.com/2023/03/fake-chatgpt-chrome-browser-extension.html) on HK saying that this extension actually is a malware and steals facebook session cookies.

anyone can verify this? is this just a false alarm/news?

for the meantime, i'll stop using this extension until i can confirm that this is safe.

**Comment by josStorer** [comment]
Here's an open-sourced and more powerful alternative, although a fledgling one: https://github.com/josStorer/chatGPTBox

**Comment by smith558** [comment]
The article is about a different extension.

**Comment by wong2** [comment]
That's correct.
